np.concatenate() 是 NumPy 中的一个函数，用于将多个数组（张量）沿指定的轴连接在一起。它的作用是创建一个新的数组，其中包含了所有输入数组的元素。以下是关于 np.concatenate() 的作用、含义和使用方法，以及一个详细示例：

作用和含义：
np.concatenate() 用于将多个数组连接在一起，形成一个更大的数组。连接可以沿指定的轴进行，可以用于水平（横向）连接或垂直（纵向）连接数组。

In [1]:
import numpy as np

# 创建两个示例数组
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# 垂直连接数组a和b
result_vertical = np.concatenate((a, b), axis=0)

# 水平连接数组a和b
result_horizontal = np.concatenate((a, b.T), axis=1)  # 注意b需要转置

print("垂直连接结果：")
print(result_vertical)

print("水平连接结果：")
print(result_horizontal)


垂直连接结果：
[[1 2]
 [3 4]
 [5 6]]
水平连接结果：
[[1 2 5]
 [3 4 6]]
