In [1]:
import numpy as np

通过对数组直接判断的方式可以有效检索出下标:
- 直接打印Frequency > 0
- 使用np.where()

In [7]:
frequency = np.array([1, 0, 2, 4, -2, 5])
print(frequency[frequency >= 0])
print(frequency > 0)


[1 0 2 4 5]
[ True False  True  True False  True]


In [9]:
print(np.where(frequency > 0))
frequency_pos_idx = np.where(frequency > 0)[0]
print(frequency_pos_idx)

(array([0, 2, 3, 5], dtype=int64),)
[0 2 3 5]
