In [3]:
import numpy as np
import torch
import torch.nn as nn

In [4]:
test1 = torch.tensor([1, 1, 1])
test2 = torch.tensor([1, 2, 3])
print(test1 @ test2)

tensor(6)


# 矩阵相乘

In [35]:
test_tensor1 = torch.tensor([0.0156, 0.0154, 0.0156, 0.0158, 0.0157, 0.0156, 0.0156, 0.0155, 0.0154,
                            0.0156, 0.0155, 0.0159, 0.0157, 0.0154, 0.0159, 0.0158, 0.0154, 0.0156,
                            0.0155, 0.0157, 0.0155, 0.0153, 0.0157, 0.0160, 0.0152, 0.0155, 0.0158,
                            0.0157, 0.0157, 0.0155, 0.0156, 0.0162, 0.0156, 0.0159, 0.0159, 0.0159,
                            0.0157, 0.0158, 0.0155, 0.0151, 0.0156, 0.0156, 0.0160, 0.0158, 0.0157,
                            0.0160, 0.0161, 0.0157, 0.0159, 0.0157, 0.0159, 0.0155, 0.0154, 0.0156,
                            0.0158, 0.0155, 0.0150, 0.0155, 0.0156, 0.0160, 0.0150, 0.0153, 0.0154,
                            0.0152]) * 64
test_tensor2 = torch.tensor([0.0156, 0.0155, 0.0158, 0.0159, 0.0158, 0.0156, 0.0159, 0.0158, 0.0157,
                            0.0159, 0.0157, 0.0160, 0.0158, 0.0158, 0.0161, 0.0158, 0.0155, 0.0157,
                            0.0156, 0.0161, 0.0156, 0.0155, 0.0158, 0.0160, 0.0153, 0.0158, 0.0157,
                            0.0158, 0.0156, 0.0157, 0.0160, 0.0159, 0.0154, 0.0159, 0.0160, 0.0160,
                            0.0156, 0.0156, 0.0153, 0.0152, 0.0155, 0.0156, 0.0158, 0.0158, 0.0157,
                            0.0161, 0.0158, 0.0155, 0.0155, 0.0156, 0.0156, 0.0155, 0.0157, 0.0150,
                            0.0154, 0.0154, 0.0149, 0.0154, 0.0156, 0.0159, 0.0149, 0.0152, 0.0149,
                            0.0148]) * 64

print(test_tensor1.shape)
print(test_tensor1 @ test_tensor2 / (64**2) * 100)

torch.Size([64])
tensor(1.5636)


# 取对角操作

In [38]:
# 1 * 1 * 4 * 4
arrange_number = torch.linspace(1, 16, 16)
arrange_number = arrange_number.reshape(1, 1, 4, 4)

diagonal_elements = arrange_number[:, :, torch.arange(arrange_number.size(-1)), torch.arange(arrange_number.size(-1))]
temperature = nn.Parameter(torch.rand(4))

# diagonal_elements = diagonal_elements * temperature
diagonal_elements = diagonal_elements * temperature
diagonal_sum = torch.einsum('ijk->ij', diagonal_elements)


tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])
tensor([[[ 1.,  6., 11., 16.]]])
torch.Size([1, 1, 4, 4])
torch.Size([1, 1, 4])
Parameter containing:
tensor([0.3004, 0.6312, 0.8082, 0.9016], requires_grad=True)
tensor([[[ 3.3291,  9.5051, 13.6107, 17.7456]]], grad_fn=<DivBackward0>)
tensor([[34.]])


In [ ]:
# device='cuda:0', grad_fn=<IndexBackward0>
similar_matrix_1 = torch.tensor([[[0.01569486, 0.01565937, 0.01565642,  ..., 0.01565932,
          0.01567657, 0.01565336],
         [0.01566275, 0.01565734, 0.01568742,  ..., 0.01569968,
          0.01564839, 0.01567465],
         [0.01566168, 0.01569930, 0.01566200,  ..., 0.01564763,
          0.01565019, 0.01570976],
         [0.01564663, 0.01564702, 0.01564354,  ..., 0.01566396,
          0.01566114, 0.01564323]],

        [[0.01564232, 0.01565255, 0.01567281,  ..., 0.01564171,
          0.01562881, 0.01562734],
         [0.01565642, 0.01564136, 0.01564042,  ..., 0.01563987,
          0.01562702, 0.01563093],
         [0.01563587, 0.01564165, 0.01563220,  ..., 0.01562954,
          0.01563282, 0.01563101],
         [0.01564705, 0.01562513, 0.01561788,  ..., 0.01563945,
          0.01563628, 0.01565172]],

        [[0.01562612, 0.01563444, 0.01562364,  ..., 0.01563311,
          0.01563279, 0.01562956],
         [0.01565880, 0.01563986, 0.01563312,  ..., 0.01564047,
          0.01561499, 0.01565013],
         [0.01563330, 0.01565649, 0.01565511,  ..., 0.01564515,
          0.01563909, 0.01563674],
         [0.01562988, 0.01565192, 0.01564197,  ..., 0.01563991,
          0.01565899, 0.01565785]],

        ...,

        [[0.01564965, 0.01565409, 0.01564270,  ..., 0.01565024,
          0.01563659, 0.01562928],
         [0.01566099, 0.01565619, 0.01563534,  ..., 0.01566024,
          0.01563789, 0.01565323],
         [0.01564687, 0.01567283, 0.01564727,  ..., 0.01562966,
          0.01562858, 0.01565296],
         [0.01565862, 0.01566135, 0.01564329,  ..., 0.01566127,
          0.01566458, 0.01563373]],

        [[0.01569193, 0.01565311, 0.01565474,  ..., 0.01563743,
          0.01563165, 0.01563219],
         [0.01566485, 0.01566012, 0.01567828,  ..., 0.01566612,
          0.01562759, 0.01565480],
         [0.01566533, 0.01567663, 0.01566781,  ..., 0.01562867,
          0.01563912, 0.01563304],
         [0.01564470, 0.01563894, 0.01563817,  ..., 0.01562962,
          0.01562154, 0.01564375]],

        [[0.01567206, 0.01564424, 0.01567429,  ..., 0.01566890,
          0.01566599, 0.01563446],
         [0.01567527, 0.01565805, 0.01566854,  ..., 0.01565999,
          0.01563870, 0.01566551],
         [0.01564588, 0.01568289, 0.01564742,  ..., 0.01563334,
          0.01563011, 0.01565637],
         [0.01563673, 0.01564119, 0.01562897,  ..., 0.01565516,
          0.01564813, 0.01562893]]])
